### ISSUE TITLE
Experiences with Linphone 4.4.7 

### ISSUE THREAD

**Issue by leukimi** [BelledonneCommunications/linphone-desktop#677] opened 2022-07-05 23:41 UTC
### Overall comment:
**User thinks the app has potential, but is complicated to operate. Many clicks. User has feeling that the functionality is there, but it is "far away and behind many clicks". User thinks it is sad that equipment on the hardware (mic, speakers, camera) is not enough to produce acceptable sound and image quality. User thinks headset is a must at the current stage, due to zero echo cancellation and poor noise reduction of background noise. It is difficult to fix things on the fly without restarting the app or terminating the call first.**

_Some of these issues for sure relate to linphone-sdk. I write them all here, because users feel that it is the app that gives them the feeling. Not many think that there is a sub-library called liblinphone, bctoolbox or similar._

It seems that calls between Linphone 4.4.7 on Debian-based systems (Debian Unstable, Ubuntu 22.04, Ubuntu-Budgie 22.04) don't crash as often as calls between Debian-based systems and Fedora 35. Archlinux/Manjaro was not tested.

Crashes are frequent on both Fedora 35 and Debian-based systems (Debian Unstable, Ubuntu 22.04, Ubuntu-Budgie 22.04).

Video freezes often after a couple of minutes. Sometimes it works to click video on/off to fix it, sometimes it doesn't help. It is heavily dependent on if user is doing something else simultaneously, such as making and sharing screen-shots.

Ephemeral messages set to 1 minute and 1 hour do not get delivered. Encrypted attachments don't get delivered.

Encrypted chats randomly asks for verification and account login during call. It says you have to call the other person to upgrade an already encrypted chat, and when obeying, a new call is started to the other part who is already in a call. Sometimes the person Linphone thinks you have to call is put on pause and gets to hear the nice pause music and doesn't understand why they get to hear music. Maybe different pause music would be more amusing.

Encrypted chats are not transferred between units, if you move to another box. You cannot continue in the same chat as from a previous machine. Deleting and setting up a new encrypted chat does not send new text messages and attachments (screenshots JPEG, GIF). It seems like it works, then user gets a red little dot which means it failed. User gets frustrated. Call hangup does not deliver messages and attachments in encrypted chats.

Chats seems to work at best when unencrypted. Encrypted chat messages, especially sharing image like a screenshot in PNG, GIF or JPEG does not get delivered.

User misses functionality to cut and paste a screenshot into linphone. It is very troublesome to first create a screenshot in PNG, then save it, then convert it to a format that the other part can open in a simple app, like JPEG or GIF.

User finds it enervating that they have to click on an image file to see what it is. Instead the file should be visible at once in the chat. Opening an attachment in a local application creates extra steps.

When User changes SIP account, it is not shown in the app. When user clicks on identity, it shows which identity is active and sending, but the main window does not display same name. After restart of the app, then Linphone App shows the correct User SIP-phone-account.

The robot-speech talks with american accent in other languages, even though Linphone has been changed to that language and have that language menus, the robot still speaks american (system language). Since many computers use english as system language, but local language in app or in a specific chat, it should be possible to change this on chat bases. (Comment: Espeak-ng offers language tweaks, usually a female voice sounds "easier to understand" than male espeak-voice but that feature of enhancement is not used.

If remote party does not pick up the phone call within the time that the small window appears, like 5 seconds, very short for slow moving hands, it is impossible to locate an answer button fast enough. Meanwhile, calling party still has calling signal long time and thinks that it rings on the other end.

Camera request should be communicated back to user, that camera request is in process, awaiting acceptance for camera by the other part. This causes double clicking after the time and generates frustration at the other end  when they clicked ok just a millisecond before the video just flashed and was gone again. Hrm. A simple "waiting for other part to accept" would slow down a second click.

Some cameras display image upside down in linphone, and there is no button to fix it (flip).

Some cameras show green lines and distorted picture in linphone, but okay and good picture in app like Cheese.

When user gets a call, and wants to insert a USB-headset for better sound quality, the call first has to be hung up and replaced so that user can change to headset.

Without headset, microphone is not muted when one part speaks, causing delayed echo back to speaking party. The remote speaker gets picked up by remote microphone and sent back.

Echo cancellation has to be adaptive and automatic. During a call, delay can change 20 milliseconds, causing no echo cancellation. Most of the time the user is told that there is no issue with echo, although the bare initiative to click on the red button to fix echo indicates that there is an issue.

Issues with ALSA drivers and adjusting levels are still notiiceable. Other part often tells the sound is garbage and asks to turn it off. Camera stutters and shows bricks quite frequent, but user can accept that as long as the sound is okay.

GSM, G729 (bcg729), BV16 (Broadvoice16) audio codecs should be enabled automatically for better compatibility. All users have difficulty to notice the codecs under "the orange line".

The Call window does not have any means to access the preferences for echo cancellation. Instead user has to go to main window, hamburger (three lines) then click to the setting... it is a lot of clicks during a call. Plus the sad feeling that it didn't get any better.

User thinks that Linphone MUST be used with a good headset with noise reduction. Linphone does not seem to do noise reduction itself, but relies on the hardware microphone to do that. Some microphones seem to pick up sound 20 meters away, very sensitive, with no noise reduction it seems.

Linphone seems to perform worse when both parties are on WiFi. If at least one part is on cable, it works better.

Sometimes, more than 10 empty encrypted chats randomly show up to the left in the main window. The button to delete a chat is located far away to the right from the chat that user has to click to delete it. That button has to be close to the chat. Multi choice chat + Delete All is a must to clear the log. Especially for privacy, you would need a 1-2 click kill switch for everything, clear all data in one go. User experiences that app needs many clicks to do even simple things.

User thinks that release version 4.4.7 is an "alpha" release with many bugs due to so many crashes. A release should not be so "buggy", user thinks.

**Comment by julonexus** [comment] 2022-07-06 08:12
Hi
Thanks for your feedback but it is not the purpose of this place. We keep trace on issues in order to resolve them when we(and the community) have the free-time to do it.
You should post it in the mailing list at linphone-users@nongnu.org or at linphone-developers@nongnu.org for technically cases.

I guess you know that the application is out after completing a test plan with few systems. We don't have the resource to do it on each environment on each user on this earth.
Also, we cannot work on a huge report like that where points are specifics. In addition, some already exists in the tracker (like text to speech languages) or about a miss-used like having to hangup to change devices where you don't have to do it (by going to the settings in audio tab to reload the device... I know this is not a good thing for user design but it is already fixed for 4.5)
- So please open new tickets for each issues with description and logs like requested in the issue template. 

If you want us to work on them in one time, you can contact us for a commercial help by completing our Typeforms [here](https://linphone.org/contact#content-bottom3) (click on "Contact Us").

That being said, there is one huge wrong behavior that exists in the SDK and that have been reveled since we introduce the encrypted chats :
If your chat room receives a timeout on ACK, the chat room is marked as left (because of the protocol). And then, you cannot communicate anymore and you have to recreate a new chat room.
The SDK team is working on it but it is not as simple.
I guess this is the cause of your not deliveries cases.

Regards

**Closed by julonexus** 2022-07-06 08:12 UTC
