### ISSUE TITLE
Call history does not show incoming/missed calles (since 5.2.3)?

### ISSUE THREAD

**Issue by AlBundy33** [BelledonneCommunications/linphone-desktop#831] opened 2024-04-08 13:41 UTC
Today I've updated from 5.1.2 to 5.2.3 and now I can not find the list of incoming/missed and outgoing calls.
Is it somewhere hidden or am I blind? 🤔

**Comment by AlBundy33** [comment] 2024-05-02 14:23
This is strange: usually I have `show_local_sip_account=0` set in my linephonerc but for tests I've reenabled the setting.
If I switch to the local sip-account which shows my local IP as server I see ALL incoming and outgoing calls.
If I switch back to my main-sip-account I see only the outgoing calls....

**Comment by AlBundy33** [comment] 2024-05-02 14:49
If I run this query on `call-history.db`
```
select *
from call_history ch
where direction = 1
order by id desc
```
I see that all outgoing calls have as callee `<sip:MyUserName@a.b.c.d;transport=udp>`
Where a.b.c.d is my vpn-IP
In my settings I have configured something like `<sip:MyUserName@asterisk.somedomain.tld;transport=udp>`

**Comment by Matt-Agnes** [comment] 2024-06-19 16:33
Someone on my team is having the same issue as this. It would be great to find a resolution.

**Comment by AlBundy33** [comment] 2024-07-25 06:42
still an issue for me too.
The only workaround is to switch the account in the upper left corner becuase all incoming calls are shown in the "default sip account" but not with the configured proxy-account. 🤔 

it seems that in earlier versions of linphone it was possible to display all calls independent from the selected account. see #397 

Not sure why Linphone isn't shown the incoming calls in my proxy-account because this is the only account I'm using.
But I have different IPs (of course) when I'm in home-office (with vpn) or in the office (without vpn)

**Comment by Ledjlale** [comment] 2024-07-25 07:50
Hi
"where direction = 1" it is about incoming call. outgoing call are direction=0. I think you just misspell, no problem.

Please post your logs and the caller logs. Your issue is more likely that your caller is calling your IP (default proxy) and not your domain (configured proxy) which is not a software bug from your side.

I'm closing this ticket because of duplication and for not matching to the template with useful info to investigate.

Regards

**Closed by Ledjlale** 2024-07-25 07:50 UTC

**Comment by Matt-Agnes** [comment] 2024-07-25 09:19
@Ledjlale what is the duplicate ticket so we can add comments to this? One of my team members still can't see missed calls on the main SIP account they use to make and receive calls. However if they switch to the other account they can see the missed calls.

**Comment by Ledjlale** [comment] 2024-07-25 09:44
It was pointed out in the previous post : https://github.com/BelledonneCommunications/linphone-desktop/issues/813
But it will be closed soon because the current status is a user issue (caller call the proxy default), which has not been confirmed by the OP and still awaiting for its feedback.

You may need to open a new ticket with the requested data.

**Comment by AlBundy33** [comment] 2024-07-25 11:50
> "where direction = 1" it is about incoming call. outgoing call are direction=0. I think you just misspell, no problem.
I known that this is for incomfing calls - the issue is about missed incoming calls.
The DB contains my vpn-ip and my local sip-account is 192.168.... which is my private network (I'm in home-office) so i'm pretty confident that someone has called this IP directly...

**Comment by Ledjlale** [comment] 2024-07-25 11:56
![dir](https://github.com/user-attachments/assets/73a6d9d3-d61f-478b-99fb-c5ca4fe62995)
 ;)

**Comment by AlBundy33** [comment] 2024-07-25 11:59
🤦‍♂️

![image](https://github.com/user-attachments/assets/6b6a2f5f-835e-4b71-843c-5866628e4a28)
I don't know what you are talking about 😄
