### ISSUE TITLE
Linphone Sluggish or Frozen Version 5 or greater

### ISSUE THREAD

**Issue by IVRNetworks** [BelledonneCommunications/linphone-desktop#781] opened 2023-08-15 17:45 UTC
### Context

Tried installing Versions 5.0.8, 5.0.10 and 5.0.18 on Windows 11. 

Cannot get to screens to even configure as app is sluggish to the point of being non responsive

### General information

- Device: Dell Lapton
- OS: Win 11
- Version of the App: 5.0.x
- Version of the SDK:

### Expected behaviour

Should allow for normal interaction, instead it acts frozen, when clicking any option from initial screen after install. Remains non responsive after a full minute waiting.

### To Reproduce

Install on Windows 11 (ran install as administrator)

### Additional context

Not possible to get logs, the app is that non responsive

**Comment by chlaudan** [comment] 2023-08-16 00:48
Recently installed in desktop with 32GB RAM and SSD, having same issue. It will function properly if I quit google drive. Not a feasible option for me.

**Comment by agemuend** [comment] 2023-08-23 06:39
This is a duplicate of #688 which is named incorrectly, because its not specific to Windows 11. It's reproducible on Windows 10 at least since 21H2 too.

**Closed** 2023-08-25 08:58 UTC
Labels: bug
