### ISSUE TITLE
Unable to see call history - Windows 4.2.2

### ISSUE THREAD

**Issue by dbachen** [BelledonneCommunications/linphone-desktop#426] opened 2020-09-01 12:48 UTC
I was asked to log this as a new issue.

Here's what happens to me using the Windows Desktop 4.2.2

- The missed call doesn't show up the "previously" log
- The missed call notification shows up as a number next to the chat looking bubble (up near my account)
- I cannot access those messages at all. Every time I click on it, it takes me to the account picker as well
- The icon in the system try will keep blinking to show me missed calls (which is annoying because I can never access them), until I restart the app

Example image:
![image](https://user-images.githubusercontent.com/10816427/91853233-e5b9d280-ec2f-11ea-8cb9-f3b6c75d64b7.png)

**Comment by julonexus** [comment] 2020-09-01 12:57
Duplicate of #384 
Please check your INVITE and REGISTER messages. If addresses are different, it comes from the SIP Server that change fields.
You received the call but there is no way to identify it with your proxies. I'll do a workaround to remove the notifications but not more.

**Closed by julonexus** 2020-09-01 12:57 UTC

**Comment by dbachen** [comment] 2020-09-01 18:56
Hi Julonexus,

Maybe I misstated something for you.

Is the expected behavior for clicking on the message notification icon to take to the account picker? Because that's what I'm reporting that it's doing. There isn't a way to see those messages, they are just showing up with the increased number and cannot be viewed.

Or are you saying because there is a mismatch in the INVITE and REGISTER, this is a false notification and won't actually show anything?

I did check those messages and I think they appear to be same, but not sure if that's true.
Here's the Register when I started the app ::
REGISTER sip:a1east.sipregistration.com SIP/2.0
From: "D Bachen" <sip:sip2022_dimtdiamondtech@a1east.sipregistration.com>

Here's the Invite when the incoming call came in and I was able to answer it ::
INVITE sip:sip2022_dimtdiamondtech@50.229.101.106:7012;transport=udp SIP/2.0
From: "WIRELESS CALLER" <sip:8566936601@198.58.40.227:5060>;tag=as2c312737
To: <sip:sip2022_dimtdiamondtech@50.229.101.106:7012;transport=udp>

**Comment by julonexus** [comment] 2020-10-09 21:16
`Is the expected behavior for clicking on the message notification icon to take to the account picker?`
Yes, this is expected.
The issue is: 
You register with sip2022_dimtdiamondtech@a1east.sipregistration.com
You receive a call with this To : sip2022_dimtdiamondtech@50.229.101.106
These are not the same address (even if IP are equal). The TO must be sip2022_dimtdiamondtech@a1east.sipregistration.com as it is used to identify a user, not a device. This field is changed by your SIP server, this is not about Linphone.

As there is no way to match your proxy with this kind of messages, I add a way to see all call logs in the current nightly build.
There
