### ISSUE TITLE
No audio output from Linphone Desktop 4.2beta with WASAPI Speakers (Realtek Audio)

### ISSUE THREAD

**Issue by vince62s** [BelledonneCommunications/linphone-desktop#347] opened 2020-04-20 18:21 UTC
same as #295 but with 4.2
is this going to be fxed ?

**Comment by trexmaster** [comment] 2020-05-17 08:44
This definitely needs to be fixed.

**Comment by julonexus** [comment] 2020-05-19 16:46
Duplicate of #295

**Closed by julonexus** 2020-05-19 16:46 UTC
