### ISSUE TITLE
No Xcode Project file

### ISSUE THREAD

**Issue by deepak2503** [BelledonneCommunications/linphone-desktop#183] opened 2018-05-26 14:54 UTC
I have Downloaded linphone-desktop for Mac OS. Successfully compiled it Everything is Ok , but in the source code there is no Xcode project file as like for other platform IOS and Android. 
Please help me I am unable to open the project in Xcode.

**Comment by Wescoeur** [comment] 2018-05-29 12:45
Duplicate of #184.

**Closed by Wescoeur** 2018-05-29 12:45 UTC
