### ISSUE TITLE
Contacts from CardDAV Server

### ISSUE THREAD

**Issue by lukasubo** [BelledonneCommunications/linphone-desktop#402] opened 2020-07-14 05:05 UTC
Hello,

Since liblinphone supports reading contacts from CardDAV servers, could this be integrated with Linphone Desktop? This would allow syncing contacts from Android.

Thanks

https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Features/Vcard4%20contacts/

**Comment by julonexus** [comment] 2020-07-14 07:39
Duplicate of #349

**Closed by julonexus** 2020-07-14 07:39 UTC
