### ISSUE TITLE
OpenGL errors at startup with Flatpak 

### ISSUE THREAD

**Issue by etamme** [BelledonneCommunications/linphone-desktop#32] opened 2017-06-15 16:44 UTC
$ flatpak run com.belledonnecommunications.linphone
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version

**Comment by etamme** [comment] 2017-06-15 16:46
glxinfo output https://gist.github.com/etamme/578deb0f32feaa51143bd4e6088bce38

**Comment by alexeymuranov** [comment] 2017-07-02 10:45
Is this on an Nvidia machine?  Could [this question](https://askubuntu.com/q/759647) and [this bug report](https://bugs.launchpad.net/snappy/+bug/1574851) for Snappy be related to this issue?

**Comment by Wescoeur** [comment] 2017-07-02 10:46
Yes it's a Nvidia issue. It must be resolved in the next release. :)

**Comment by alexeymuranov** [comment] 2017-07-02 10:49
Thanks.  Is there, by any chance, anything that can be done on the user side meanwhile (purging Nvidia drivers, etc.)?

**Comment by ghismary** [comment] 2017-07-03 08:31
Unfortunately, you cannot do anything for this problem with the 4.0 release. Please wait for the next release. It should get released next week.

**Comment by Wescoeur** [comment] 2017-07-23 09:31
Must be fixed in the next release. You can freely reopen this issue if needed.

**Closed by Wescoeur** 2017-07-23 09:31 UTC
Labels: bug, difficulty: hard (weeks), in progress, severity: critical

**Comment by alexeymuranov** [comment] 2017-07-23 11:48
Works for me, thank you!

**Comment by wiskos** [comment] 2018-02-27 18:43
Hello,
I did a "git clone git://git.linphone.org/linphone-desktop.git --recursive" and compiled the project.
When launching linphone-desktop, I get the same message : "libGL error: No matching fbConfigs or visuals found libGL error: failed to load driver: swrast"
The release I got seems to be 4.1.0 - 2017-07-19 (Changelog) so could have the same problem as described here.
How could I get 4.1.1, please?

**Comment by wiskos** [comment] 2018-02-28 19:28
I already get 4.1.1 indeed and have the problem with a Redhat Enterprise 7 / Centos 7:
[root@integ4 linphone-desktop.copie]# OUTPUT/desktop/bin/linphone
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[20:22:21:587][0x180ef00][Info]"Use locale: fr_FR"
[20:22:21:844][0x180ef00][Info]"Running app..."
[20:22:21:846][0x180ef00][Info]"Library paths:" ("/home/tmp/SOFTPHONE/LINPHONE/qt-5.9.4_64/rh/plugins", "/usr/lib64/kde4/plugins", "/usr/lib/kde4/plugins", "/home/tmp/SOFTPHONE/LINPHONE/linphone-desktop.copie/OUTPUT/desktop/bin")
[20:22:21:847][0x1861300][Info]"Launch async linphone core creation."
[20:22:21:853][0x180ef00][Info]"Activated selectors:" ("custom", "5.9", "fr_FR", "unix", "linux", "rhel")
[20:22:21:853][0x180ef00][Info]"Registering types..."
[20:22:21:854][0x180ef00][Info]"Registering shared types..."
[20:22:21:855][0x180ef00][Info]"Registering tool types..."
[20:22:21:855][0x180ef00][Info]"Registering shared tool types..."
[20:22:21:895][0x180ef00][Warning]"Errors found in `Notification` component 5:" (qrc:/ui/modules/Linphone/Notifications/NotificationRecordingCompleted.qml:5:1: Type NotificationBasic unavailable, qrc:/ui/modules/Linphone/Notifications/NotificationBasic.qml:1:1: module "QtQuick" is not installed)
[20:22:22:035][0x1861300][Info]"Set `Friends` path: `/root/.local/share/linphone/friends.db`"
[20:22:22:037][0x1861300][Info]"Set `CallLogs` path: `/root/.local/share/linphone/call-history.db`"
[20:22:22:038][0x1861300][Info]"Set `Chat` path: `/root/.local/share/linphone/message-history.db`

**Comment by johnramsden** [comment] 2018-03-20 16:37
I started getting this error recently as well. I assume it's related to an nvidia update. Is a fix in the works?

**Comment by mike-mccormick** [comment] 2018-04-09 10:17
I can confirm I'm getting the same on freshly installed nvidia drivers - can we re-open this as an issue? Happy to test changes if needed.

**Comment by tux-rampage** [comment] 2018-05-25 09:08
This is still an issue Ubuntu 18.04 with nvidia legacy drivers
