### ISSUE TITLE
[Bug]: Install fails with 'Linphone is running'

### ISSUE THREAD

**Issue by DrDallas** [BelledonneCommunications/linphone-desktop#705] opened 2022-10-24 14:19 UTC
### Context

I am an engineer responsible for deploying the application for a customer; I do not use Linphone.

### General information

- Device: Any
- OS: Windows 10
- Version of the App: 4.4.8, 4.4.9, 4.4.10
- Version of the SDK: unk

When starting the installer (by double clicking or from the command line), the user (local admin or not) receives the following error message: 
Linphone is running. Please close it first from the application menu and restart the installation.

See the "Additional Context" for the problem discussion and resolution.

### Expected behaviour

The application installer starts.

### To Reproduce

1. Create a folder somewhere (e.g., c:\temp) named Linphone
2. Download the installer and place it in the newly created folder (e.g., c:\temp\Linphone)
3. Open the folder in Explorer
4. Launch the installer
5. Error message is displayed
6. Try launching installer from command line (leaving the Explorer window open)
7. Error message is displayed
8. Close the Explorer window
9. Launch the installer from the command line (the Explorer window is now closed).
10. The installer starts

### Additional context

The issue is that the installer looks for Windows with the title "Linphone".  You can also get the same error if you open Notepad with a file named Linphone. 

To correct, the installer should look for a unique Linphone process / signature instead of static text in window titles.

**Comment by julonexus** [comment] 2022-10-24 14:47
Already fixed for 5.0.
Duplicate of #695

**Closed by julonexus** 2022-10-24 14:47 UTC
Labels: bug
